# A generic, single database configuration.

[alembic]
# path to migration scripts
script_location = alembic

# template used to generate migration files
# file_template = %%(rev)s_%%(slug)s

# sys.path path, will be prepended to sys.path if present.
# defaults to the current working directory.
prepend_sys_path = .

# timezone to use when rendering the date within the migration file
# as well as the filename.
# If specified, requires the python-dateutil library that can understand
# timestamps in the format name/[±]HH:MM[:SS[.UUUUUU]][Z|±HH[:]MM]]] generally
# does not include 'Z' or '±'. If not specified the timestamp is formatted
# using ISO8601 format in UTC timezone.
# timezone =

# max length of characters to apply to the
# "slug" field
# truncate_slug_length = 40

# set to 'true' to run the environment file directly, false to allow
# it to be imported first and then executed.
# This is useful for debugging.
# sourceless = false

# version path separator; defaults to colon
# version_path_separator = :

# set to 'true' to search for the script_location above the current directory
# instead of inside it.
# search_parent_directories = false

# Revision change identifier truncation length
# truncate_change_id = false

# Controls how many migrations will be run before a new branch
# is created for subsequent migrations.
# max_branches = 1

# Controls whether migrations should be ordered or not.
# If true, then migrations will be ordered by their revision identifier
# instead of their dependency relationships.
# order_by_revision = false

# set to 'true' to allow .pyc and .pyo files to be detected as
# imports in 'version_locations', 'custom_commands', or 'copy_from'
# directives
# sourceless = false

# Logging configuration
[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic
qualname =

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S